baseURL = "https://hugo-theme-shell.netlify.app/"
languageCode = "en-us"
title = "Aimt@blog:~# Hello World"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "monokai"
    userName = "Aimt"
    pcName = "Blog"
    workDir = "mydir"
    profile = "profile.txt"
    description = """
    Hi I am Aimt!
    Nice to meet you!
    """

    [Params.Tree]
    use = true
    files = [
        ["C/C++", "/"],
        ["Python", "/"],
        ["Go", "/works/go.md"],
        ["Hugo", "/works/hugo.md"]
    ]
